package com.jep.esb.wsvalidacionesexistencia.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2023-09-20T10:20:06.311-05:00
 * Generated source version: 3.5.2
 *
 */
@WebService(targetNamespace = "http://servicios.mercurio.servisoft.com.co/", name = "gestionExpedienteService")
@XmlSeeAlso({ObjectFactory.class})
public interface GestionExpedienteService {


    @WebMethod
    @RequestWrapper(localName = "validacionExistencia", targetNamespace = "http://servicios.mercurio.servisoft.com.co/", className = "co.com.servisoft.mercurio.servicios.ValidacionExistencia")
    @ResponseWrapper(localName = "validacionExistenciaResponse", targetNamespace = "http://servicios.mercurio.servisoft.com.co/", className = "co.com.servisoft.mercurio.servicios.ValidacionExistenciaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.jep.esb.wsvalidacionesexistencia.model.GestionExpedienteValidarResponse validacionExistencia(

        @WebParam(name = "body", targetNamespace = "")
        com.jep.esb.wsvalidacionesexistencia.model.GestionExpedienteValidarRequets body
    );


}
