package com.jep.esb.wsvalidacionesexistencia.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.2
 * 2023-09-20T10:20:06.339-05:00
 * Generated source version: 3.5.2
 *
 */
@WebServiceClient(name = "gestionExpedienteService",
                  wsdlLocation = "file:/Users/davidfonseca/Desktop/JEP/Proyectos/ESBWK-amos-qoco/src/main/resources/gestionExpedienteService_1.wsdl",
                  targetNamespace = "http://servicios.mercurio.servisoft.com.co/")
public class GestionExpedienteService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://servicios.mercurio.servisoft.com.co/", "gestionExpedienteService");
    public final static QName GestionExpedienteServicePort = new QName("http://servicios.mercurio.servisoft.com.co/", "gestionExpedienteServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/davidfonseca/Desktop/JEP/Proyectos/ESBWK-amos-qoco/src/main/resources/gestionExpedienteService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GestionExpedienteService_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/davidfonseca/Desktop/JEP/Proyectos/ESBWK-amos-qoco/src/main/resources/gestionExpedienteService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GestionExpedienteService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GestionExpedienteService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionExpedienteService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GestionExpedienteService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GestionExpedienteService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GestionExpedienteService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GestionExpedienteService
     */
    @WebEndpoint(name = "gestionExpedienteServicePort")
    public GestionExpedienteService getGestionExpedienteServicePort() {
        return super.getPort(GestionExpedienteServicePort, GestionExpedienteService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionExpedienteService
     */
    @WebEndpoint(name = "gestionExpedienteServicePort")
    public GestionExpedienteService getGestionExpedienteServicePort(WebServiceFeature... features) {
        return super.getPort(GestionExpedienteServicePort, GestionExpedienteService.class, features);
    }

}
